// moon-phase.js — day-signature kit: moon-phase background (COSTAR / TLGE).
// GENERATED by COSTAR-Project/day-signature/build_moon_kit.py — do not edit;
// regenerate there and re-copy. Data: canonical golden calendar CSV
// (2000-11-25 … 2051-01-12, 1241 new/full moon events, PT dates).
//
// Contract (ruled 2026-07-23): sets on <html> the CSS custom properties
// `--moon` (0 = new-moon black … 1 = full-moon white) and `--moon-bg`
// (the day's background as a ready-made rgb() color — use this where a
// CSS pipeline rejects calc() inside color functions), plus the attribute
// `data-moon-ink` ("white" when --moon < 0.5, else "black"). Site
// stylesheets map these signals onto their palettes. The value changes
// at 00:01 PT (the calendar's native day boundary, +1 min). Preview with
// ?moon=D in the URL, where D is a phase day 0-29 (0 = New Moon,
// 15 = Full Moon; 16-29 mirror the waxing days). No network calls.
(function () {
  var EPOCH = Date.UTC(2000, 10, 25); // first event date (PT), as UTC days
  var FIRST_TYPE = "N";        // "N" new or "F" full
  var GAPS = "geffegefegefegefeffffefegegefegeffegefegefeffffefegegefegeffefffefegefffeffffegefegefeffffefegefegeffffefffegefefffeffegefegefffeffffefegefegeffefffegefegeffffefegefegefeffffegefegefffeffegefegefeffffefffegefegeffefffefegefffeffffegefegefeffffefegegefegeffefffegdgefffeffegefegegeffefffefegefegeffffefegegefeffffefegefegefffeffffegdgefffeffefffegefegeffffefegefegefeffffegefegefffeffegefegefeffffefffegefegeffefffegdgefffeffffegefegefeffffefegefegeffffegefegefefffeffegefegeffffefffefegefegeffegefegegefeffffefegefegeffefffegegdgefffeffegefegefegeffegefegefegeffefffegefegeffffefegefegefeffffefffegefegeffegefegdgefffeffffegefegeffefffefegefegeffffegefegefeffffefegefegeffffefffegdgefffeffegefegefffeffffefegefegeffefffegefegefffeffegefegefeffffegefegefffeffefffegefegeffefffegefegefeffffefegegefegeffegefegefeffffefegegefegeffefffefegefffeffffegefegefeffffefegefegeffffefffegefefffeffegefegefffeffffefegefegeffefffegefegeffffefegefegefeffffegefegefffeffegefegefeffffefffegefegeffefffefegefffeffffegefegefeffffefegegefeffffefffegdgefffeffegefegegeffefffefegefegeffffefegegefefffeffegefegefffeffegegdgefffeffefffegefegeffffefegefegefeffffegefegefffeffegefegefeffffefffegefegeffefffefegefffeffffegefegefeffffefegefegeffffegefegefefffeffegefeg";                    // base36 day-gaps between events

  var days = [0];
  for (var i = 0; i < GAPS.length; i++) {
    days.push(days[i] + parseInt(GAPS.charAt(i), 36));
  }

  function ptDayIndex(now) {
    // the calendar day flips at 00:01 PT: shift back 1 min, take the PT date
    var parts = new Intl.DateTimeFormat("en-CA", {
      timeZone: "America/Los_Angeles",
      year: "numeric", month: "2-digit", day: "2-digit"
    }).format(new Date(now.getTime() - 60000));
    var d = parts.split("-");
    return Math.round((Date.UTC(+d[0], d[1] - 1, +d[2]) - EPOCH) / 86400000);
  }

  function brightness(day) {
    if (day < days[0] || day > days[days.length - 1]) return null;
    var lo = 0, hi = days.length - 1;
    while (lo < hi) { // greatest event index with days[i] <= day
      var mid = (lo + hi + 1) >> 1;
      if (days[mid] <= day) lo = mid; else hi = mid - 1;
    }
    var evenIsNew = FIRST_TYPE === "N";
    var atNew = (lo % 2 === 0) === evenIsNew;
    if (days[lo] === day) return atNew ? 0 : 1;
    var t = (day - days[lo]) / (days[lo + 1] - days[lo]);
    var toward = (1 - Math.cos(Math.PI * t)) / 2; // cosine illumination
    return atNew ? toward : 1 - toward;
  }

  function msUntilNextFlip(now) {
    var pt = new Intl.DateTimeFormat("en-GB", {
      timeZone: "America/Los_Angeles",
      hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false
    }).format(now).split(":");
    var since = ((+pt[0] * 60 + +pt[1]) * 60 + +pt[2]) * 1000;
    var flip = 61000; // 00:01:00 PT + 1s slack
    var until = flip - since;
    if (until <= 0) until += 86400000;
    return Math.min(until + 1000, 86400000);
  }

  function overrideValue() {
    // ?moon=D — phase day 0-29 on the nominal 30-day wheel (Kevin,
    // 2026-07-23): 0 = New Moon, 15 = Full Moon, 16-29 mirror the waxing
    // days. Converted to brightness via the same cosine illumination.
    var m = (location.search + location.hash).match(/[?&#]moon=([0-9.]+)/);
    if (!m) return null;
    var d = parseFloat(m[1]);
    if (isNaN(d)) return null;
    d = Math.max(0, Math.min(29, d));
    if (d > 15) d = 30 - d;
    return (1 - Math.cos(2 * Math.PI * d / 30)) / 2;
  }

  function apply() {
    var v = overrideValue();
    if (v === null) v = brightness(ptDayIndex(new Date()));
    var root = document.documentElement;
    if (v === null) { // outside dataset: leave site defaults untouched
      root.style.removeProperty("--moon");
      root.style.removeProperty("--moon-bg");
      root.removeAttribute("data-moon-ink");
      return;
    }
    var g = Math.round(v * 255);
    root.style.setProperty("--moon", v.toFixed(4));
    root.style.setProperty("--moon-bg", "rgb(" + g + "," + g + "," + g + ")");
    root.setAttribute("data-moon-ink", v < 0.5 ? "white" : "black");
  }

  apply();
  (function schedule() {
    setTimeout(function () { apply(); schedule(); },
               msUntilNextFlip(new Date()));
  })();
})();
